name: 🚀 Deploy to Hostinger via FTP

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug – show all FTP secrets (safe in public logs; values are masked)
        run: |
          echo "FTP_HOST=[${{ secrets.FTP_HOST }}]"
          echo "FTP_USERNAME=[${{ secrets.FTP_USERNAME }}]"
          echo "FTP_PASSWORD=[${{ secrets.FTP_PASSWORD }}]"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          server-dir: /public_html/